SELECT * FROM hackatonFinancialFundraising.DOADOR;

INSERT INTO DOADOR (ID_DOADOR,NOME_DOADOR,CPF,EMAIL)
VALUES (1,'Ronaldinho','12345678910','ronaldinho@jibulani.bol');

INSERT INTO DOADOR (ID_DOADOR,NOME_DOADOR,CPF,EMAIL)
VALUES (2,'Takumi','86868686866','hachirouku@drift.D');

INSERT INTO DOADOR (ID_DOADOR,NOME_DOADOR,CPF,EMAIL)
VALUES (3,'Sonic','11111111111','sonic@sega.jp');

INSERT INTO DOADOR (ID_DOADOR,NOME_DOADOR,CPF,EMAIL)
VALUES (4,'X','21XX21XX211','X@maverickhunter.cap');

INSERT INTO DOADOR (ID_DOADOR,NOME_DOADOR,CPF,EMAIL)
VALUES (5,'Stonks','00000000000','stonks@jurasicpark.dino');

