
create view VW_PROCESSA_REPASSE AS SELECT SUM(VALOR),ID_LOJA FROM (SELECT distinct ID_LOJA ,VALOR FROM DOACOES)as TESTE group by ID_LOJA;

SELECT * FROM VW_PROCESSA_REPASSE;




 
create view VW_PROCESSA_REPASSE AS SELECT SUM(VALOR),ID_LOJA FROM (SELECT distinct ID_LOJA ,VALOR FROM DOACOES WHERE ID_PERIODO IN (SELECT ID_PERIODO FROM PERIODO WHERE PAGO IS FALSE))as TESTE group by ID_LOJA;


DROP VIEW VW_PROCESSA_REPASSE;